####**Mounting the Drive**

In [64]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


#**Pre-processing**

#####Reading in Data

In [68]:
import pandas as pd
ct = pd.read_csv('/content/gdrive/My Drive/groupeddata.csv')
ct = ct.drop(columns = ['num'])
ct

Incident Type  Offense Hour of Day Offense Day of Week  ... Day  Month  Year
0            Assault                    3              Friday  ...   1     11  2019
1            Assault                   23            Saturday  ...   2     11  2019
2            Assault                   18            Saturday  ...   9     11  2019
3            Assault                   20              Monday  ...   4     11  2019
4            Assault                    8              Friday  ...   8     11  2019
...              ...                  ...                 ...  ...  ..    ...   ...
150257        Weapon                    0            Thursday  ...  10      5  2012
150258        Weapon                   10             Tuesday  ...  18      7  2017
150259        Weapon                   12              Friday  ...  22     11  2013
150260        Weapon                   20            Thursday  ...  14      9  2017
150261        Weapon                   17              Friday  ...  15      6  2018

[150262 rows x 10 columns]

In [70]:
#ct2=ct.groupby('Incident Type', as_index = False)['Incident Type'].agg(['count'])
#ct2.sort_values('count')

count    22
dtype: int64

#####Encoding string values

In [71]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
ct['Incident Type'] = le.fit_transform(ct['Incident Type'].astype(str))
ct['Incident Type'] = le.fit_transform(ct['Incident Type'])

le2 = preprocessing.LabelEncoder()
ct['Offense Day of Week'] = le2.fit_transform(ct['Offense Day of Week'].astype(str))
ct['Offense Day of Week'] = le2.fit_transform(ct['Offense Day of Week'])

le3 = preprocessing.LabelEncoder()
ct['Address'] = le2.fit_transform(ct['Address'].astype(str))
ct['Address'] = le2.fit_transform(ct['Address'])

ct['Incident Type'].nunique()

22

#####Dividing into train and test sets

In [72]:
from sklearn.model_selection import train_test_split
y = ct['Incident Type']
ct = ct.drop(columns= 'Incident Type')

X_train, X_test, y_train, y_test = train_test_split(ct, y, test_size=0.20)

print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(120209, 9) (120209,)
(30053, 9) (30053,)


#**Classification**

####**SGD**

Fit

In [73]:
%%time
from sklearn import model_selection, linear_model
clf = linear_model.SGDClassifier(loss='log')
clf.fit(X_train, y_train)

CPU times: user 3min, sys: 0 ns, total: 3min
Wall time: 3min


Accuracy

In [74]:
clf.score(X_test, y_test)

0.08894286760057232

Confusion Matrix

In [76]:
import numpy as np
np.set_printoptions(threshold=np.inf, linewidth = 2026)
from sklearn.metrics import confusion_matrix
y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   0,    0,    0,  296,    0,    0,    0,   15,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1391,    0,    0,    0,   45,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1382,    0,    0,    0,   99,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 2622,    0,    0,    0,   73,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,  180,    0,    0,    0,   21,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1160,    0,    0,    0,   65,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,  222,    0,    0,    0,    8,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,

####**KNN**

Fit

In [77]:
%%time
from sklearn import neighbors, metrics
clf2 = neighbors.KNeighborsClassifier()
clf2.fit(X_train, y_train)

CPU times: user 168 ms, sys: 5.06 ms, total: 173 ms
Wall time: 246 ms


Accuracy

In [78]:
clf2.score(X_test, y_test)

0.17069843276877517

Confusion Matrix

In [79]:
y_pred = clf2.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  15,   26,   35,   47,    3,   16,    0,   11,   42,   19,   10,    0,    3,   17,    0,    2,    9,   32,    6,   12,    6,    0],
       [  38,  237,  133,  213,   12,   66,    8,   54,  166,   61,   43,    6,   43,   74,    3,   16,   42,  125,   19,   58,   19,    0],
       [  44,  154,  261,  174,   13,   75,    7,   88,  164,   83,   25,    4,   19,   57,    2,    7,   39,  136,   13,   79,   37,    0],
       [  79,  265,  262,  743,   17,  134,   24,   67,  336,  127,   58,   11,   41,   90,    1,   28,   95,  219,   17,   60,   19,    2],
       [   6,   27,   20,   37,   15,    4,    2,    7,    7,   18,    3,    0,    5,    5,    0,    2,    5,   19,    0,   17,    2,    0],
       [  31,  110,  143,  219,   11,   87,    9,   58,  170,   50,   41,    6,   23,   55,    1,   13,   44,   91,    7,   37,   18,    1],
       [   7,   18,   26,   45,    1,   11,    5,    8,   36,   13,    7,    0,    7,    9,    0,    0,    7,   19,    1,    8,    2,    0],
       [  46,

####**Random Forest**

Fit

In [80]:
%%time
from sklearn import ensemble
clf3 = ensemble.RandomForestClassifier()
clf3.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


CPU times: user 3.28 s, sys: 225 ms, total: 3.51 s
Wall time: 3.59 s


Accuracy

In [81]:
clf3.score(X_test, y_test)

0.20613582670615246

Confusion Matrix

In [82]:
y_pred = clf3.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   5,   18,   28,   43,    1,   16,    1,   14,   56,   17,    9,    4,    8,    9,    3,    2,   11,   24,   16,   20,    6,    0],
       [  11,  174,  100,  182,    7,   64,    4,   57,  177,  117,   73,   11,   49,  106,    2,   14,   64,  137,   17,   37,   30,    3],
       [  18,   86,  229,  180,   12,   63,    5,   76,  200,   97,   27,    7,   43,   67,    6,   18,   54,  141,   18,   89,   44,    1],
       [  18,  160,  191,  914,   10,  107,   16,   80,  350,  123,   69,   16,   56,  121,    5,   46,  107,  198,   28,   47,   31,    2],
       [   2,   11,   11,   28,   27,    8,    1,    6,   14,   21,    4,    1,    7,    6,    2,    4,    9,   16,    6,   15,    2,    0],
       [  14,   61,   89,  224,    4,  113,    5,   59,  172,   66,   48,   11,   31,   84,    2,   18,   52,   92,   19,   37,   18,    6],
       [   4,   20,   13,   38,    0,   11,    7,   11,   51,   11,    5,    3,    3,   13,    2,    2,    6,   16,    2,    8,    1,    3],
       [  16,

####**XGB**

Fit

In [83]:
%%time
import xgboost as xgb
clf4 = xgb.XGBClassifier()
clf4.fit(X_train, y_train)

CPU times: user 1min 51s, sys: 161 ms, total: 1min 51s
Wall time: 1min 52s


Accuracy

In [84]:
clf4.score(X_test, y_test)

0.23075899244667752

Confusion Matrix

In [85]:
y_pred = clf4.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   0,    0,   19,   35,    0,    0,    0,    0,   95,   29,    0,    0,    0,    3,    0,    0,    1,   98,   12,   17,    2,    0],
       [   0,   12,   41,  162,    4,    2,    0,    7,  320,  121,   47,    0,   63,   46,    0,    0,    6,  526,   18,   55,    6,    0],
       [   0,    1,  179,  188,    2,    0,    0,    1,  387,  127,   25,    0,    0,   23,    0,    0,    0,  432,   27,   71,   18,    0],
       [   0,    0,   39,  820,    1,    1,    0,    1,  732,  146,   41,    0,    3,   37,    0,    0,   20,  757,   35,   61,    1,    0],
       [   0,    0,    7,   37,    5,    0,    0,    0,   34,   28,    0,    0,    0,    0,    0,    0,    0,   49,    3,   38,    0,    0],
       [   0,    0,   52,  254,    0,    1,    0,    0,  352,   85,   27,    0,    0,   46,    0,    0,    4,  319,   23,   60,    2,    0],
       [   0,    0,    1,   52,    0,    0,    0,    0,   81,   12,    4,    0,    0,    1,    0,    0,    1,   68,    2,    8,    0,    0],
       [   0,

####**LightGBM**

Fit

In [86]:
%%time
import lightgbm as lgb
clf5 = lgb.LGBMClassifier()
clf5.fit(X_train, y_train)

CPU times: user 27.3 s, sys: 209 ms, total: 27.5 s
Wall time: 27.6 s


Accuracy

In [87]:
clf5.score(X_test, y_test)

0.26004059494892356

Confusion Matrix

In [88]:
y_pred = clf5.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   0,    2,   16,   39,    0,    0,    0,    2,  109,   30,    0,    0,    2,    4,    0,    0,    5,   53,   10,   31,    8,    0],
       [   0,   78,   56,  203,    2,    7,    0,   28,  356,  123,   56,    0,   37,   80,    0,    0,   25,  282,   18,   68,   17,    0],
       [   1,   19,  176,  194,    2,    8,    4,   26,  422,  129,   23,    1,    4,   43,    0,    0,   11,  239,   25,  118,   35,    1],
       [   0,    7,   35, 1025,    2,   20,    4,    5,  810,  156,   50,    0,    4,   50,    0,    0,   42,  385,   31,   64,    3,    2],
       [   0,    0,    9,   38,   18,    1,    1,    3,   34,   29,    0,    0,    1,    3,    1,    0,    3,   28,    4,   28,    0,    0],
       [   1,    5,   46,  274,    1,   13,    0,    9,  397,   90,   31,    1,    0,   47,    0,    1,   12,  197,   27,   65,    6,    2],
       [   0,    2,    2,   61,    0,    1,    3,    0,   90,   12,    4,    0,    0,    5,    0,    0,    5,   34,    3,    8,    0,    0],
       [   0,

####**MLP**

Fit

In [89]:
%%time
from sklearn import neural_network
clf6 = neural_network.MLPClassifier()
clf6.fit(X_train, y_train)

CPU times: user 3min 47s, sys: 1min 57s, total: 5min 45s
Wall time: 2min 53s


Accuracy

In [90]:
clf6.score(X_test, y_test)

0.14780554353974645

Confusion Matrix

In [92]:
y_pred = clf6.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   0,    0,   87,    0,    0,   16,    0,    0,    0,    5,  191,    0,    0,    1,    0,    0,    3,    0,    0,    6,    2,    0],
       [   0,    4,  376,    0,    0,   62,    0,    0,    0,   21,  910,    0,    0,    0,    0,    0,   18,    0,    1,   34,    7,    3],
       [   0,    6,  462,    0,    0,   71,    0,    0,    0,   34,  810,    0,    0,    2,    0,    0,   23,    0,    0,   52,   11,   10],
       [   2,    6,  641,    0,    0,  124,    0,    0,    0,   44, 1750,    0,    0,    0,    0,    0,   42,    0,    0,   60,   24,    2],
       [   0,    1,   55,    0,    0,   10,    0,    0,    0,    7,  113,    0,    0,    0,    0,    0,    4,    0,    0,   10,    1,    0],
       [   1,    6,  324,    0,    0,   54,    0,    0,    0,   26,  741,    0,    0,    0,    0,    0,   24,    0,    0,   33,   12,    4],
       [   0,    0,   51,    0,    0,    4,    0,    0,    0,    6,  152,    0,    0,    0,    0,    0,    3,    0,    0,   10,    3,    1],
       [   0,

###**Parameter tuning**

Manual

In [121]:
%%time
import lightgbm as lgb
clf5 = lgb.LGBMClassifier(boosting_type='dart', num_leaves=40, max_depth=7, learning_rate=0.4, n_estimators=100, max_bin=500, objective='multiclass', min_data_in_leaf = 20)
clf5.fit(X_train, y_train)

CPU times: user 1min 35s, sys: 176 ms, total: 1min 36s
Wall time: 1min 36s


In [120]:
clf5.score(X_test, y_test)

0.25375170532060026

#####Trying different resampling techniques

In [95]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [96]:
clf5 = lgb.LGBMClassifier()
clf5.fit(X_resampled, y_resampled)
clf5.score(X_test, y_test)

0.20114464446145144

In [0]:
from imblearn.under_sampling import RandomUnderSampler
res = RandomUnderSampler()
X_res, y_res = res.fit_resample(X_train, y_train)

In [99]:
clf5 = lgb.LGBMClassifier()
clf5.fit(X_res, y_res)
clf5.score(X_test, y_test)

0.15659002429042027

In [0]:
from imblearn.over_sampling import SMOTE, ADASYN
X_resampled, y_resampled = SMOTE().fit_resample(X_train, y_train)

In [101]:
clf5 = lgb.LGBMClassifier()
clf5.fit(X_resampled, y_resampled)
clf5.score(X_test, y_test)

0.25075699597377965

In [102]:
y_pred = clf5.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   2,    3,   15,   35,    1,    2,    2,    2,   99,   23,    3,    1,    1,    5,    0,    0,    5,   53,   20,   28,   11,    0],
       [   0,   92,   45,  175,   17,   13,   22,   38,  306,  106,   83,    4,   48,   68,    0,    2,   23,  265,   32,   63,   27,    7],
       [   9,   26,  170,  176,   23,   17,   17,   31,  358,  116,   38,    5,    8,   37,    7,    2,   10,  226,   61,   90,   46,    8],
       [   5,    7,   30,  960,   32,   40,   29,   13,  671,  150,   89,    7,    9,   45,    7,    3,   35,  403,   78,   60,   11,   11],
       [   0,    0,    7,   31,   38,    4,    0,    2,   28,   26,    1,    1,    0,    2,    2,    2,    5,   23,    8,   18,    1,    2],
       [   2,    8,   40,  240,   25,   30,    6,   10,  341,   86,   51,    4,    4,   40,    4,    2,   11,  205,   47,   51,   10,    8],
       [   1,    3,    2,   52,    2,    1,   10,    1,   85,   11,   12,    0,    0,    3,    0,    0,    3,   34,    3,    6,    0,    1],
       [   4,

In [0]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)

In [105]:
clf5 = lgb.LGBMClassifier()
clf5.fit(X_resampled, y_resampled)
clf5.score(X_test, y_test)

0.14574252154527

In [0]:
from imblearn.combine import SMOTETomek
smote_tomek = SMOTETomek(random_state=0)
X_resampled, y_resampled = smote_tomek.fit_resample(X_train, y_train)

In [107]:
clf5 = lgb.LGBMClassifier()
clf5.fit(X_resampled, y_resampled)
clf5.score(X_test, y_test)

0.24546634279439655

In [108]:
y_pred = clf5.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[   3,    2,   16,   41,    1,    2,    7,    1,   87,   30,    4,    3,    1,    5,    3,    0,    7,   36,   22,   27,   11,    2],
       [   4,  100,   46,  163,   17,   12,   31,   34,  323,  109,   90,    5,   44,   70,    4,    3,   29,  217,   29,   68,   30,    8],
       [  18,   23,  170,  167,   26,   22,   27,   32,  342,  126,   49,    5,    7,   35,    9,    4,   11,  185,   68,   97,   48,   10],
       [   6,   17,   32,  913,   42,   36,   49,   12,  689,  148,  109,    4,   14,   51,   13,    7,   56,  313,   87,   70,   15,   12],
       [   0,    1,    8,   28,   41,    3,    0,    1,   31,   21,    1,    1,    1,    2,    1,    2,    6,   25,    8,   18,    1,    1],
       [   2,   11,   51,  205,   27,   33,   11,   11,  345,   86,   62,    7,    4,   50,    6,    4,   25,  148,   56,   57,   12,   12],
       [   1,    2,    1,   53,    3,    3,   15,    0,   80,   11,   10,    1,    1,    7,    1,    0,    2,   25,    5,    6,    0,    3],
       [   9,